spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      routes:
        #        - id: path_route
        #          uri: https://new.qq.com
        #          predicates:
        #            - Path=/red/{segment},/blue/{segment},/ch/finance
        #          # localhost:18080/ch/finance 会跳转至 https://new.qq.com/ch/finance
        - id: service_route
          uri: lb://SERVICE-PROVIDER
          predicates:
            - Path=/provider/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  application:
    name: gateway-service
server:
  port: 18080


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5