eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5
spring:
  application:
    name: service-provider
server:
  port: 18081