eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18761/eureka/
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 5

# feign默认配置 default, default->clientName则是具体FeignClient配置
# readTimeout超时优先级: 调用方 指定配置 > 默认配置 > Client中Provider定义的超时时间
feign:
  client:
    config:
      default:
        connectTimeout: 1000
        readTimeout: 3000 # feign调用接口阻塞时间超过此值则 Read time out executing xxx
        loggerLevel: FULL
      service-provider:
        connectTimeout: 1000
        readTimeout: 10000
        loggerLevel: FULL
  # feign 熔断设置
  hystrix:
    enabled: false
  # feign httpclient
  httpclient:
    enabled: true
    max-connections-per-route: 1
    max-connections: 3
    follow-redirects: true
    time-to-live-unit: seconds
    time-to-live: 60
    connection-timeout: 3000

spring:
  application:
    name: service-consumer
#  cloud:
#    circuitbreaker:
#      hystrix:
#        enabled: false
server:
  port: 18082

hystrix:
  command:
    test:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
# 全局设置
ribbon:
    readTimeout: 6000
    ConnectTimeout: 6000
    OkToRetryOnAllOperations: true
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 2